// frontend-vue/src/components/UsageStats.vue
<script setup lang="ts">
import { ref, watch } from 'vue'
import { getPoolKeyStats, getAccessKeyStats, getStatsOverview } from '@/api/admin'
import UsageTable from './UsageTable.vue'
import UsageChart from './UsageChart.vue'
import type { PoolKeyStats, AccessKeyStats, StatsOverview } from '@/types'

const hours = ref(24)
const loading = ref(false)
const poolStats = ref<PoolKeyStats[]>([])
const accessStats = ref<AccessKeyStats[]>([])
const overview = ref<StatsOverview | null>(null)

const chartRef = ref<InstanceType<typeof UsageChart>>()

async function loadStats() {
  loading.value = true
  try {
    const [poolData, accessData, overviewData] = await Promise.all([
      getPoolKeyStats(hours.value),
      getAccessKeyStats(hours.value),
      getStatsOverview(hours.value),
    ])
    poolStats.value = poolData.keys || []
    accessStats.value = accessData.keys || []
    overview.value = overviewData
  } catch {
    // ignore
  } finally {
    loading.value = false
  }
}

watch(hours, loadStats)
loadStats()
</script>

<template>
  <div class="usage-stats-section" v-loading="loading">
    <div class="usage-stats-header">
      <span class="usage-stats-title">📊 用量统计</span>
      <el-radio-group v-model="hours" size="small">
        <el-radio-button :value="24">24h</el-radio-button>
        <el-radio-button :value="168">7d</el-radio-button>
        <el-radio-button :value="720">30d</el-radio-button>
      </el-radio-group>
    </div>

    <!-- 概览卡片 -->
    <div v-if="overview" class="overview-row">
      <div class="overview-item">
        <span class="overview-value">{{ overview.total_requests }}</span>
        <span class="overview-label">总请求数</span>
      </div>
      <div class="overview-item">
        <span class="overview-value">{{ overview.active_pool_keys }}</span>
        <span class="overview-label">活跃号池 Key</span>
      </div>
      <div class="overview-item">
        <span class="overview-value">{{ overview.active_access_keys }}</span>
        <span class="overview-label">活跃访问 Key</span>
      </div>
    </div>

    <!-- 双列统计表格 -->
    <el-row :gutter="16" class="usage-tables-row">
      <el-col :xs="24" :sm="12">
        <UsageTable
          title="号池 Key 用量"
          :rows="poolStats"
          name-key="name"
        />
      </el-col>
      <el-col :xs="24" :sm="12">
        <UsageTable
          title="访问 Key 用量"
          :rows="accessStats"
          name-key="name"
          :show-total="true"
        />
      </el-col>
    </el-row>

    <!-- 趋势图表 -->
    <UsageChart ref="chartRef" :hours="hours" />
  </div>
</template>

<style scoped>
.usage-stats-section {
  margin-bottom: 24px;
}

.usage-stats-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 12px;
}

.usage-stats-title {
  font-size: var(--text-base);
  font-weight: var(--weight-semibold);
  color: var(--text);
}

.overview-row {
  display: flex;
  gap: 24px;
  margin-bottom: 12px;
  padding: 8px 16px;
  background: var(--el-bg-color);
  border-radius: var(--el-border-radius-base);
  border: 1px solid var(--el-border-color-lighter);
}

.overview-item {
  display: flex;
  flex-direction: column;
  align-items: center;
}

.overview-value {
  font-family: var(--font-mono);
  font-size: var(--text-lg);
  font-weight: var(--weight-bold);
  color: var(--ws-pool);
}

.overview-label {
  font-size: var(--text-xs);
  color: var(--text3);
  margin-top: 2px;
}

.usage-tables-row {
  margin-bottom: 16px;
}
</style>

// frontend/src/components/usage/UsageStats.tsx
import { useState, useEffect } from 'react'
import { Card, Segmented, Spin, Row, Col, Statistic, message } from 'antd'
import { getStatsOverview, getPoolKeyStats, getAccessKeyStats } from '@/api/admin'
import type { StatsOverview as StatsOverviewType, PoolKeyStats, AccessKeyStats } from '@/types'
import { UsageTable } from './UsageTable'
import { UsageChart } from './UsageChart'

export function UsageStats() {
  const [hours, setHours] = useState<24 | 168 | 720>(24)
  const [overview, setOverview] = useState<StatsOverviewType | null>(null)
  const [poolStats, setPoolStats] = useState<PoolKeyStats[]>([])
  const [accessStats, setAccessStats] = useState<AccessKeyStats[]>([])
  const [loading, setLoading] = useState(false)

  useEffect(() => {
    const loadData = async () => {
      setLoading(true)
      try {
        const [overviewData, poolData, accessData] = await Promise.all([
          getStatsOverview(hours),
          getPoolKeyStats(hours),
          getAccessKeyStats(hours),
        ])
        setOverview(overviewData)
        setPoolStats(poolData.keys || [])
        setAccessStats(accessData.keys || [])
      } catch (e: any) {
        message.error('加载统计数据失败')
      } finally {
        setLoading(false)
      }
    }
    loadData()
  }, [hours])

  const poolTableRows = poolStats.map(s => ({
    id: s.key_id,
    name: s.name || `Key #${s.key_id}`,
    requests: s.total_requests,
    promptTokens: s.total_prompt_tokens,
    completionTokens: s.total_completion_tokens,
  }))

  const accessTableRows = accessStats.map(s => ({
    id: s.access_key_id,
    name: s.name || `Access #${s.access_key_id}`,
    requests: s.total_requests,
    promptTokens: s.total_prompt_tokens,
    completionTokens: s.total_completion_tokens,
  }))

  return (
    <Spin spinning={loading}>
      <div className="section-card">
        <div className="card-header">
          <h2 className="card-title">用量统计</h2>
          <Segmented
            options={[
              { label: '24 小时', value: 24 },
              { label: '7 天', value: 168 },
              { label: '30 天', value: 720 },
            ]}
            value={hours}
            onChange={(v) => setHours(v as 24 | 168 | 720)}
          />
        </div>

        {overview && (
          <Row gutter={[16, 16]} className="section-card__row">
            <Col xs={24} sm={8}>
              <Card>
                <Statistic title="总请求数" value={overview.total_requests} />
              </Card>
            </Col>
            <Col xs={24} sm={8}>
              <Card>
                <Statistic title="活跃号池 Key" value={overview.active_pool_keys} />
              </Card>
            </Col>
            <Col xs={24} sm={8}>
              <Card>
                <Statistic title="活跃访问 Key" value={overview.active_access_keys} />
              </Card>
            </Col>
          </Row>
        )}

        <Row gutter={[16, 16]}>
          <Col xs={24} lg={12}>
            <UsageTable
              title="号池 Key 用量"
              rows={poolTableRows}
              showTotal={false}
            />
          </Col>
          <Col xs={24} lg={12}>
            <UsageTable
              title="访问 Key 用量"
              rows={accessTableRows}
              showTotal={true}
            />
          </Col>
        </Row>

        <Card title="Token 用量趋势" className="section-card__spaced">
          <UsageChart hours={hours} />
        </Card>
      </div>
    </Spin>
  )
}
