// frontend/src/components/access/CreateAccessKeyModal.tsx
import { useState } from 'react'
import { Modal, Form, Input, InputNumber, DatePicker, message } from 'antd'
import type { CreateAccessKeyInput } from '@/types'

interface Props {
  open: boolean
  onClose: () => void
  onSubmit: (input: CreateAccessKeyInput) => Promise<void>
}

export function CreateAccessKeyModal({ open, onClose, onSubmit }: Props) {
  const [form] = Form.useForm()
  const [loading, setLoading] = useState(false)

  const handleSubmit = async () => {
    try {
      const values = await form.validateFields()
      setLoading(true)
      // 日期格式：YYYY-MM-DD HH:mm:ss
      const expiresAt = values.expires_at
        ? values.expires_at.format('YYYY-MM-DD HH:mm:ss')
        : null
      await onSubmit({
        name: values.name?.trim() || null,
        rpm_limit: values.rpm_limit || 0,
        tpm_limit: values.tpm_limit || 0,
        expires_at: expiresAt,
      })
      form.resetFields()
    } catch (e: any) {
      if (e.errorFields) return
      message.error('提交失败: ' + (e.message || '未知错误'))
    } finally {
      setLoading(false)
    }
  }

  return (
    <Modal
      title="创建访问 Key"
      open={open}
      onCancel={() => {
        form.resetFields()
        onClose()
      }}
      onOk={handleSubmit}
      confirmLoading={loading}
      width={500}
    >
      <Form form={form} layout="vertical">
        <Form.Item name="name" label="名称">
          <Input placeholder="给这个 Key 起个名字（可选）" />
        </Form.Item>

        <div className="form-row">
          <Form.Item name="rpm_limit" label="RPM 限制">
            <InputNumber min={0} placeholder="0 = 不限" />
          </Form.Item>
          <Form.Item name="tpm_limit" label="TPM 限制">
            <InputNumber min={0} placeholder="0 = 不限" />
          </Form.Item>
        </div>

        <Form.Item name="expires_at" label="过期时间">
          <DatePicker showTime placeholder="选择过期时间（可选）" />
        </Form.Item>
      </Form>
    </Modal>
  )
}

// frontend/src/components/CreateAccessKeyModal.vue
<script setup lang="ts">
import { reactive } from 'vue'
import type { CreateAccessKeyInput } from '@/types'

const modelValue = defineModel<boolean>({ required: true })
const emit = defineEmits<{ submit: [input: CreateAccessKeyInput] }>()

const form = reactive({
  name: '',
  rpm_limit: 0,
  tpm_limit: 0,
  expires_at: '',
})

function handleSubmit() {
  const expireVal = form.expires_at
  const input: CreateAccessKeyInput = {
    name: form.name || null,
    rpm_limit: form.rpm_limit || 0,
    tpm_limit: form.tpm_limit || 0,
    expires_at: expireVal ? expireVal.replace('T', ' ') : null,
  }
  emit('submit', input)
}

function handleClosed() {
  Object.assign(form, { name: '', rpm_limit: 0, tpm_limit: 0, expires_at: '' })
}
</script>

<template>
  <el-dialog v-model="modelValue" title="创建访问 Key" width="480px" @closed="handleClosed">
    <el-form :model="form" label-width="120px" label-position="top">
      <el-form-item label="名称">
        <el-input v-model="form.name" placeholder="如：张三的 Key" />
      </el-form-item>
      <el-row :gutter="16">
        <el-col :span="12">
          <el-form-item label="RPM 限制 (0=不限)">
            <el-input-number v-model="form.rpm_limit" :min="0" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="TPM 限制 (0=不限)">
            <el-input-number v-model="form.tpm_limit" :min="0" />
          </el-form-item>
        </el-col>
      </el-row>
      <el-form-item label="过期时间">
        <el-date-picker
          v-model="form.expires_at"
          type="datetime"
          placeholder="留空则永不过期"
          value-format="YYYY-MM-DDTHH:mm:ss"
        />
      </el-form-item>
    </el-form>
    <template #footer>
      <el-button @click="modelValue = false">取消</el-button>
      <el-button type="success" @click="handleSubmit">创建</el-button>
    </template>
  </el-dialog>
</template>
