// frontend/src/components/pool/AddPoolKeyModal.tsx
import { useState, useEffect, useMemo, useRef } from 'react'
import { Modal, Form, Input, Select, InputNumber, message } from 'antd'
import type { AddPoolKeyInput } from '@/types'
import { useModelPresets } from '@/hooks/useModelPresets'
import { PLATFORM_DEFAULTS } from '@/config/platformDefaults'

interface Props {
  open: boolean
  onClose: () => void
  onSubmit: (input: AddPoolKeyInput) => Promise<void>
}

export function AddPoolKeyModal({ open, onClose, onSubmit }: Props) {
  const [form] = Form.useForm()
  const [loading, setLoading] = useState(false)
  const { ensurePresetsLoaded, getPresetModelsForPlatform } = useModelPresets()

  const platform = Form.useWatch('platform', form) || 'xiaomi'

  // 弹窗打开时加载预设数据
  useEffect(() => {
    if (open) ensurePresetsLoaded()
  }, [open, ensurePresetsLoaded])

  // 切换平台时自动填充 URL 和默认模型
  const platformInitRef = useRef<string | null>(null)

  useEffect(() => {
    if (!open) {
      platformInitRef.current = null
      return
    }
    // 跳过弹窗刚打开时的首次触发（此时 form 已有 initialValues）
    if (platformInitRef.current === null) {
      platformInitRef.current = platform
      return
    }
    if (platformInitRef.current === platform) return
    platformInitRef.current = platform

    const defaults = PLATFORM_DEFAULTS[platform]
    if (!defaults) return

    form.setFieldsValue({
      openai_url: defaults.openai_url,
      claude_url: defaults.claude_url,
      models: defaults.default_models.length > 0 ? defaults.default_models : [],
    })
  }, [platform, open, form])

  // 动态 placeholder
  const openaiPlaceholder = useMemo(() => {
    if (platform === 'anthropic') return 'Anthropic 中转站通常不使用 OpenAI 协议'
    return 'https://api.example.com/v1'
  }, [platform])

  const claudePlaceholder = useMemo(() => {
    if (platform === 'anthropic') return 'https://your-relay.example.com'
    return 'https://api.example.com'
  }, [platform])

  const presetModels = useMemo(() => getPresetModelsForPlatform(platform), [platform, getPresetModelsForPlatform])

  const handleSubmit = async () => {
    try {
      const values = await form.validateFields()
      // 验证：URL 至少填一个
      if (!values.openai_url?.trim() && !values.claude_url?.trim()) {
        message.warning('OpenAI URL 和 Claude URL 至少填写一个')
        return
      }
      // 清理 models
      const modelList = (values.models || []).map((s: string) => s.trim()).filter(Boolean)
      if (modelList.length === 0) {
        message.warning('请输入至少一个模型')
        return
      }

      setLoading(true)
      await onSubmit({
        platform: values.platform,
        name: values.name?.trim() || null,
        api_key: values.api_key,
        openai_url: values.openai_url || '',
        claude_url: values.claude_url || '',
        models: modelList,
        tpm_limit: values.tpm_limit || 0,
        rpm_limit: values.rpm_limit || 0,
        source: values.source?.trim() || null,
        note: values.note?.trim() || null,
      })
      form.resetFields()
    } catch (e: any) {
      if (e.errorFields) return // 表单验证失败
      message.error('提交失败: ' + (e.message || '未知错误'))
    } finally {
      setLoading(false)
    }
  }

  return (
    <Modal
      title="添加号池 Key"
      open={open}
      onCancel={() => {
        form.resetFields()
        onClose()
      }}
      onOk={handleSubmit}
      confirmLoading={loading}
      width={600}
    >
      <Form
        form={form}
        layout="vertical"
        initialValues={{
          platform: 'xiaomi',
          openai_url: PLATFORM_DEFAULTS.xiaomi.openai_url,
          claude_url: PLATFORM_DEFAULTS.xiaomi.claude_url,
          models: PLATFORM_DEFAULTS.xiaomi.default_models,
        }}
      >
        <Form.Item name="platform" label="平台" rules={[{ required: true, message: '请选择平台' }]}>
          <Select placeholder="选择平台">
            <Select.Option value="xiaomi">小米</Select.Option>
            <Select.Option value="iflytek">讯飞</Select.Option>
            <Select.Option value="anthropic">Anthropic</Select.Option>
          </Select>
        </Form.Item>

        <Form.Item name="name" label="名称">
          <Input placeholder="给这个 Key 起个名字（可选）" />
        </Form.Item>

        <Form.Item name="api_key" label="API Key" rules={[{ required: true, message: '请输入 API Key' }]}>
          <Input.Password placeholder="sk-..." />
        </Form.Item>

        <Form.Item name="openai_url" label="OpenAI 兼容端点">
          <Input placeholder={openaiPlaceholder} />
        </Form.Item>

        <Form.Item name="claude_url" label="Claude 兼容端点">
          <Input placeholder={claudePlaceholder} />
        </Form.Item>

        <Form.Item name="models" label="支持的模型">
          <Select
            mode="tags"
            placeholder="输入模型名称后回车"
            options={presetModels.map(m => ({ label: m, value: m }))}
          />
        </Form.Item>

        <div className="form-row">
          <Form.Item name="tpm_limit" label="TPM 限制">
            <InputNumber min={0} placeholder="0 = 不限" />
          </Form.Item>
          <Form.Item name="rpm_limit" label="RPM 限制">
            <InputNumber min={0} placeholder="0 = 不限" />
          </Form.Item>
        </div>

        <Form.Item name="source" label="来源">
          <Input placeholder="例如：linux.do" />
        </Form.Item>

        <Form.Item name="note" label="备注">
          <Input.TextArea rows={2} placeholder="备注信息（可选）" />
        </Form.Item>
      </Form>
    </Modal>
  )
}

// frontend-vue/src/components/AddPoolKeyModal.vue
<script setup lang="ts">
import { reactive, computed, watch } from 'vue'
import { ElMessage } from 'element-plus'
import type { AddPoolKeyInput } from '@/types'
import { useModelPresets } from '@/composables/useModelPresets'

const modelValue = defineModel<boolean>({ required: true })
const emit = defineEmits<{ submit: [input: AddPoolKeyInput] }>()

const { ensurePresetsLoaded, getPresetModelsForPlatform } = useModelPresets()

const form = reactive({
  platform: 'xiaomi',
  name: '',
  api_key: '',
  openai_url: '',
  claude_url: '',
  models: [] as string[],
  tpm_limit: 0,
  rpm_limit: 0,
  source: '',
  note: '',
})

const openaiPlaceholder = computed(() => {
  if (form.platform === 'anthropic') return 'Anthropic 中转站通常不使用 OpenAI 协议'
  return 'https://api.example.com/v1'
})

const claudePlaceholder = computed(() => {
  if (form.platform === 'anthropic') return 'https://your-relay.example.com'
  return 'https://api.example.com'
})

const presetModels = computed(() => getPresetModelsForPlatform(form.platform))

// 对话框打开时加载预设数据
watch(modelValue, (visible) => {
  if (visible) ensurePresetsLoaded()
})

function handleSubmit() {
  // 基本验证
  if (!form.api_key.trim()) {
    ElMessage.warning('请输入 API Key')
    return
  }
  if (!form.openai_url.trim() && !form.claude_url.trim()) {
    ElMessage.warning('OpenAI URL 和 Claude URL 至少填写一个')
    return
  }
  // 清理 models：去除每项空白和空项
  const modelList = form.models.map(s => s.trim()).filter(Boolean)
  if (modelList.length === 0) {
    ElMessage.warning('请输入至少一个模型')
    return
  }
  const input: AddPoolKeyInput = {
    platform: form.platform,
    name: form.name.trim() || null,
    api_key: form.api_key.trim(),
    openai_url: form.openai_url.trim(),
    claude_url: form.claude_url.trim(),
    models: modelList,
    tpm_limit: form.tpm_limit || 0,
    rpm_limit: form.rpm_limit || 0,
    source: form.source.trim() || null,
    note: form.note.trim() || null,
  }
  emit('submit', input)
}

function handleClosed() {
  Object.assign(form, {
    platform: 'xiaomi',
    name: '',
    api_key: '',
    openai_url: '',
    claude_url: '',
    models: [],
    tpm_limit: 0,
    rpm_limit: 0,
    source: '',
    note: '',
  })
}
</script>

<template>
  <el-dialog v-model="modelValue" title="添加号池 Key" width="640px" @closed="handleClosed">
    <el-form :model="form" label-width="100px" label-position="top">
      <el-row :gutter="16">
        <el-col :span="12">
          <el-form-item label="平台" required>
            <el-select v-model="form.platform">
              <el-option label="小米 (xiaomi)" value="xiaomi" />
              <el-option label="讯飞 (iflytek)" value="iflytek" />
              <el-option label="Anthropic (anthropic)" value="anthropic" />
            </el-select>
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="名称">
            <el-input v-model="form.name" placeholder="可选，用于识别该 Key" />
          </el-form-item>
        </el-col>
      </el-row>
      <el-form-item label="API Key" required>
        <el-input v-model="form.api_key" placeholder="输入上游 API Key" />
      </el-form-item>
      <el-row :gutter="16">
        <el-col :span="12">
          <el-form-item label="OpenAI URL">
            <el-input v-model="form.openai_url" :placeholder="openaiPlaceholder" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="Claude URL">
            <el-input v-model="form.claude_url" :placeholder="claudePlaceholder" />
          </el-form-item>
        </el-col>
      </el-row>
      <el-text type="info" size="small">
        OpenAI URL 和 Claude URL 至少填写一个；只配置一种时，该 Key 只用于对应协议。
      </el-text>
      <el-form-item label="上游可用模型" required>
        <el-select
          v-model="form.models"
          multiple
          filterable
          allow-create
          default-first-option
          placeholder="选择或输入模型名称"
        >
          <el-option
            v-for="model in presetModels"
            :key="model"
            :label="model"
            :value="model"
          />
        </el-select>
        <el-text type="info" size="small">
          从下拉列表选择预设模型，或直接输入自定义模型名。
        </el-text>
      </el-form-item>
      <el-row :gutter="16">
        <el-col :span="12">
          <el-form-item label="TPM (0=不限)">
            <el-input-number v-model="form.tpm_limit" :min="0" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="RPM (0=不限)">
            <el-input-number v-model="form.rpm_limit" :min="0" />
          </el-form-item>
        </el-col>
      </el-row>
      <el-row :gutter="16">
        <el-col :span="12">
          <el-form-item label="来源">
            <el-input v-model="form.source" placeholder="可选" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="备注">
            <el-input v-model="form.note" placeholder="可选" />
          </el-form-item>
        </el-col>
      </el-row>
    </el-form>
    <template #footer>
      <el-button @click="modelValue = false">取消</el-button>
      <el-button type="primary" @click="handleSubmit">添加</el-button>
    </template>
  </el-dialog>
</template>
