// frontend/src/components/access/EditAccessKeyModal.tsx
import { useState, useEffect } from 'react'
import { Modal, Form, Input, InputNumber, DatePicker, Descriptions, Tag, message } from 'antd'
import dayjs from 'dayjs'
import type { AccessKey, UpdateAccessKeyInput } from '@/types'

interface Props {
  open: boolean
  accessKey: AccessKey | null
  onClose: () => void
  onSubmit: (id: number, input: UpdateAccessKeyInput) => Promise<void>
}

export function EditAccessKeyModal({ open, accessKey, onClose, onSubmit }: Props) {
  const [form] = Form.useForm()
  const [loading, setLoading] = useState(false)

  useEffect(() => {
    if (accessKey && open) {
      form.setFieldsValue({
        name: accessKey.name,
        rpm_limit: accessKey.rpm_limit,
        tpm_limit: accessKey.tpm_limit,
        expires_at: accessKey.expires_at ? dayjs(accessKey.expires_at) : null,
      })
    }
  }, [accessKey, open, form])

  const handleSubmit = async () => {
    if (!accessKey) return
    try {
      const values = await form.validateFields()
      setLoading(true)
      // 日期格式：YYYY-MM-DD HH:mm:ss
      const expiresAt = values.expires_at
        ? values.expires_at.format('YYYY-MM-DD HH:mm:ss')
        : null
      await onSubmit(accessKey.id, {
        name: values.name?.trim() || null,
        rpm_limit: values.rpm_limit || 0,
        tpm_limit: values.tpm_limit || 0,
        expires_at: expiresAt,
      })
    } catch (e: any) {
      if (e.errorFields) return
      message.error('提交失败: ' + (e.message || '未知错误'))
    } finally {
      setLoading(false)
    }
  }

  const formatTime = (t: string | null) => {
    if (!t) return '-'
    return new Date(t).toLocaleString('zh-CN')
  }

  return (
    <Modal
      title={`编辑访问 Key #${accessKey?.id}`}
      open={open}
      onCancel={() => {
        form.resetFields()
        onClose()
      }}
      onOk={handleSubmit}
      confirmLoading={loading}
      width={500}
    >
      {/* 只读信息 */}
      {accessKey && (
        <Descriptions column={2} size="small" bordered className="config-section">
          <Descriptions.Item label="ID">{accessKey.id}</Descriptions.Item>
          <Descriptions.Item label="Key">
            <code className="text-label">{accessKey.key.slice(0, 12)}...</code>
          </Descriptions.Item>
          <Descriptions.Item label="状态">
            <Tag color={accessKey.status === 'active' ? 'success' : 'error'}>{accessKey.status}</Tag>
          </Descriptions.Item>
          <Descriptions.Item label="最后使用">{formatTime(accessKey.last_used_at)}</Descriptions.Item>
          <Descriptions.Item label="创建时间" span={2}>{formatTime(accessKey.created_at)}</Descriptions.Item>
        </Descriptions>
      )}

      <Form form={form} layout="vertical">
        <Form.Item name="name" label="名称">
          <Input placeholder="给这个 Key 起个名字（可选）" />
        </Form.Item>

        <div className="form-row">
          <Form.Item name="rpm_limit" label="RPM 限制">
            <InputNumber min={0} placeholder="0 = 不限" />
          </Form.Item>
          <Form.Item name="tpm_limit" label="TPM 限制">
            <InputNumber min={0} placeholder="0 = 不限" />
          </Form.Item>
        </div>

        <Form.Item name="expires_at" label="过期时间">
          <DatePicker showTime placeholder="选择过期时间（可选）" />
        </Form.Item>
      </Form>
    </Modal>
  )
}

// frontend-vue/src/components/EditAccessKeyModal.vue
<script setup lang="ts">
import { reactive, watch } from 'vue'
import type { AccessKey, UpdateAccessKeyInput } from '@/types'

const modelValue = defineModel<boolean>({ required: true })

const props = defineProps<{
  accessKey: AccessKey | null
}>()

const emit = defineEmits<{ submit: [id: number, input: UpdateAccessKeyInput] }>()

const form = reactive({
  name: '',
  rpm_limit: 0,
  tpm_limit: 0,
  expires_at: '',
})

function toDatePickerValue(value: string | null): string {
  return value ? value.replace(' ', 'T').substring(0, 19) : ''
}

function fillForm(key: AccessKey | null) {
  Object.assign(form, {
    name: key?.name || '',
    rpm_limit: key?.rpm_limit || 0,
    tpm_limit: key?.tpm_limit || 0,
    expires_at: toDatePickerValue(key?.expires_at || null),
  })
}

watch(
  () => [modelValue.value, props.accessKey] as const,
  ([visible, key]) => {
    if (visible) fillForm(key)
  },
  { immediate: true },
)

function handleSubmit() {
  if (!props.accessKey) return
  const input: UpdateAccessKeyInput = {
    name: form.name.trim() || null,
    rpm_limit: form.rpm_limit || 0,
    tpm_limit: form.tpm_limit || 0,
    expires_at: form.expires_at ? form.expires_at.replace('T', ' ') : null,
  }
  emit('submit', props.accessKey.id, input)
}
</script>

<template>
  <el-dialog v-model="modelValue" title="编辑访问 Key" width="520px">
    <el-form :model="form" label-width="120px" label-position="top">
      <el-row :gutter="16">
        <el-col :span="8">
          <el-form-item label="ID">
            <el-input :model-value="accessKey?.id ?? ''" disabled />
          </el-form-item>
        </el-col>
        <el-col :span="16">
          <el-form-item label="状态">
            <el-input :model-value="accessKey?.status || ''" disabled />
          </el-form-item>
        </el-col>
      </el-row>
      <el-form-item label="访问 Key">
        <el-input :model-value="accessKey?.key || ''" disabled />
      </el-form-item>
      <el-form-item label="名称">
        <el-input v-model="form.name" placeholder="如：张三的 Key" />
      </el-form-item>
      <el-row :gutter="16">
        <el-col :span="12">
          <el-form-item label="RPM 限制 (0=不限)">
            <el-input-number v-model="form.rpm_limit" :min="0" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="TPM 限制 (0=不限)">
            <el-input-number v-model="form.tpm_limit" :min="0" />
          </el-form-item>
        </el-col>
      </el-row>
      <el-form-item label="过期时间">
        <el-date-picker
          v-model="form.expires_at"
          type="datetime"
          placeholder="留空则永不过期"
          value-format="YYYY-MM-DDTHH:mm:ss"
        />
      </el-form-item>
      <el-row :gutter="16">
        <el-col :span="12">
          <el-form-item label="最后使用">
            <el-input :model-value="accessKey?.last_used_at || '-'" disabled />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="创建时间">
            <el-input :model-value="accessKey?.created_at || '-'" disabled />
          </el-form-item>
        </el-col>
      </el-row>
    </el-form>
    <template #footer>
      <el-button @click="modelValue = false">取消</el-button>
      <el-button type="success" @click="handleSubmit">保存</el-button>
    </template>
  </el-dialog>
</template>
