// frontend/src/components/EditPoolKeyModal.vue
<script setup lang="ts">
import { reactive, watch } from 'vue'
import { ElMessage } from 'element-plus'
import type { PoolKey, UpdatePoolKeyInput } from '@/types'

const modelValue = defineModel<boolean>({ required: true })

const props = defineProps<{
  poolKey: PoolKey | null
}>()

const emit = defineEmits<{ submit: [id: number, input: UpdatePoolKeyInput] }>()

const form = reactive({
  platform: 'xiaomi',
  name: '',
  api_key: '',
  openai_url: '',
  claude_url: '',
  models: '',
  tpm_limit: 0,
  rpm_limit: 0,
  source: '',
  note: '',
})

function fillForm(key: PoolKey | null) {
  Object.assign(form, {
    platform: key?.platform || 'xiaomi',
    name: key?.name || '',
    api_key: key?.api_key || '',
    openai_url: key?.openai_url || '',
    claude_url: key?.claude_url || '',
    models: key?.models.join(', ') || '',
    tpm_limit: key?.tpm_limit || 0,
    rpm_limit: key?.rpm_limit || 0,
    source: key?.source || '',
    note: key?.note || '',
  })
}

watch(
  () => [modelValue.value, props.poolKey] as const,
  ([visible, key]) => {
    if (visible) fillForm(key)
  },
  { immediate: true },
)

function handleSubmit() {
  if (!props.poolKey) return
  if (!form.openai_url.trim() && !form.claude_url.trim()) {
    ElMessage.warning('OpenAI URL 和 Claude URL 至少填写一个')
    return
  }

  const modelList = form.models.split(',').map(s => s.trim()).filter(Boolean)
  if (modelList.length === 0) {
    ElMessage.warning('请输入至少一个模型')
    return
  }

  emit('submit', props.poolKey.id, {
    platform: form.platform,
    name: form.name.trim() || null,
    api_key: form.api_key.trim() || null,
    openai_url: form.openai_url.trim(),
    claude_url: form.claude_url.trim(),
    models: modelList,
    tpm_limit: form.tpm_limit || 0,
    rpm_limit: form.rpm_limit || 0,
    source: form.source.trim() || null,
    note: form.note.trim() || null,
  })
}
</script>

<template>
  <el-dialog v-model="modelValue" title="编辑号池 Key" width="640px">
    <el-form :model="form" label-width="100px" label-position="top">
      <el-row :gutter="16">
        <el-col :span="12">
          <el-form-item label="ID">
            <el-input :model-value="poolKey?.id ?? ''" disabled />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="表格显示">
            <el-input :model-value="poolKey?.key_prefix || ''" disabled />
          </el-form-item>
        </el-col>
      </el-row>
      <el-row :gutter="16">
        <el-col :span="12">
          <el-form-item label="平台" required>
            <el-select v-model="form.platform">
              <el-option label="小米 (xiaomi)" value="xiaomi" />
              <el-option label="讯飞 (iflytek)" value="iflytek" />
            </el-select>
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="名称">
            <el-input v-model="form.name" placeholder="可选，用于识别该 Key" />
          </el-form-item>
        </el-col>
      </el-row>
      <el-form-item label="API Key">
        <el-input v-model="form.api_key" placeholder="留空则保留当前密钥" />
      </el-form-item>
      <el-row :gutter="16">
        <el-col :span="12">
          <el-form-item label="OpenAI URL">
            <el-input v-model="form.openai_url" placeholder="https://api.example.com/v1" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="Claude URL">
            <el-input v-model="form.claude_url" placeholder="https://api.example.com" />
          </el-form-item>
        </el-col>
      </el-row>
      <el-text type="info" size="small">
        OpenAI URL 和 Claude URL 至少填写一个；只配置一种时，该 Key 只用于对应协议。
      </el-text>
      <el-form-item label="上游可用模型 (逗号分隔)" required>
        <el-input v-model="form.models" placeholder="mimo-v2.5-pro, astron-code-latest" />
        <el-text type="info" size="small">
          客户端请求任意模型时，服务会自动映射到这里配置的可用模型。
        </el-text>
      </el-form-item>
      <el-row :gutter="16">
        <el-col :span="12">
          <el-form-item label="TPM (0=不限)">
            <el-input-number v-model="form.tpm_limit" :min="0" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="RPM (0=不限)">
            <el-input-number v-model="form.rpm_limit" :min="0" />
          </el-form-item>
        </el-col>
      </el-row>
      <el-row :gutter="16">
        <el-col :span="12">
          <el-form-item label="来源">
            <el-input v-model="form.source" placeholder="可选" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="备注">
            <el-input v-model="form.note" placeholder="可选" />
          </el-form-item>
        </el-col>
      </el-row>
      <el-row :gutter="16">
        <el-col :span="12">
          <el-form-item label="状态">
            <el-input :model-value="poolKey?.status || ''" disabled />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="创建时间">
            <el-input :model-value="poolKey?.created_at || ''" disabled />
          </el-form-item>
        </el-col>
      </el-row>
    </el-form>
    <template #footer>
      <el-button @click="modelValue = false">取消</el-button>
      <el-button type="primary" @click="handleSubmit">保存</el-button>
    </template>
  </el-dialog>
</template>

// frontend/src/components/pool/EditPoolKeyModal.tsx
import { useState, useEffect, useMemo } from 'react'
import { Modal, Form, Input, Select, InputNumber, Descriptions, Tag, message } from 'antd'
import type { PoolKey, UpdatePoolKeyInput } from '@/types'
import { useModelPresets } from '@/hooks/useModelPresets'

interface Props {
  open: boolean
  poolKey: PoolKey | null
  onClose: () => void
  onSubmit: (id: number, input: UpdatePoolKeyInput) => Promise<void>
}

export function EditPoolKeyModal({ open, poolKey, onClose, onSubmit }: Props) {
  const [form] = Form.useForm()
  const [loading, setLoading] = useState(false)
  const { ensurePresetsLoaded, getPresetModelsForPlatform } = useModelPresets()

  const platform = Form.useWatch('platform', form) || poolKey?.platform || 'xiaomi'

  useEffect(() => {
    if (open) ensurePresetsLoaded()
  }, [open, ensurePresetsLoaded])

  useEffect(() => {
    if (poolKey && open) {
      form.setFieldsValue({
        platform: poolKey.platform,
        name: poolKey.name,
        api_key: '', // 留空保留原密钥
        openai_url: poolKey.openai_url,
        claude_url: poolKey.claude_url,
        models: poolKey.models,
        tpm_limit: poolKey.tpm_limit,
        rpm_limit: poolKey.rpm_limit,
        source: poolKey.source,
        note: poolKey.note,
      })
    }
  }, [poolKey, open, form])

  const openaiPlaceholder = useMemo(() => {
    if (platform === 'anthropic') return 'Anthropic 中转站通常不使用 OpenAI 协议'
    return 'https://api.example.com/v1'
  }, [platform])

  const claudePlaceholder = useMemo(() => {
    if (platform === 'anthropic') return 'https://your-relay.example.com'
    return 'https://api.example.com'
  }, [platform])

  const presetModels = useMemo(() => getPresetModelsForPlatform(platform), [platform, getPresetModelsForPlatform])

  const handleSubmit = async () => {
    if (!poolKey) return
    try {
      const values = await form.validateFields()
      if (!values.openai_url?.trim() && !values.claude_url?.trim()) {
        message.warning('OpenAI URL 和 Claude URL 至少填写一个')
        return
      }
      const modelList = (values.models || []).map((s: string) => s.trim()).filter(Boolean)
      if (modelList.length === 0) {
        message.warning('请输入至少一个模型')
        return
      }

      setLoading(true)
      await onSubmit(poolKey.id, {
        platform: values.platform,
        name: values.name?.trim() || null,
        api_key: values.api_key?.trim() || null, // 留空则保留原密钥
        openai_url: values.openai_url || '',
        claude_url: values.claude_url || '',
        models: modelList,
        tpm_limit: values.tpm_limit || 0,
        rpm_limit: values.rpm_limit || 0,
        source: values.source?.trim() || null,
        note: values.note?.trim() || null,
      })
    } catch (e: any) {
      if (e.errorFields) return
      message.error('提交失败: ' + (e.message || '未知错误'))
    } finally {
      setLoading(false)
    }
  }

  const formatTime = (t: string | null) => {
    if (!t) return '-'
    return new Date(t).toLocaleString('zh-CN')
  }

  return (
    <Modal
      title={`编辑号池 Key #${poolKey?.id}`}
      open={open}
      onCancel={() => {
        form.resetFields()
        onClose()
      }}
      onOk={handleSubmit}
      confirmLoading={loading}
      width={600}
    >
      {/* 只读信息 */}
      {poolKey && (
        <Descriptions column={2} size="small" bordered className="config-section">
          <Descriptions.Item label="ID">{poolKey.id}</Descriptions.Item>
          <Descriptions.Item label="Key 前缀">
            <code>{poolKey.key_prefix}</code>
          </Descriptions.Item>
          <Descriptions.Item label="状态">
            <Tag color={poolKey.status === 'active' ? 'success' : 'error'}>{poolKey.status}</Tag>
          </Descriptions.Item>
          <Descriptions.Item label="创建时间">{formatTime(poolKey.created_at)}</Descriptions.Item>
        </Descriptions>
      )}

      <Form form={form} layout="vertical">
        <Form.Item name="platform" label="平台" rules={[{ required: true, message: '请选择平台' }]}>
          <Select placeholder="选择平台">
            <Select.Option value="xiaomi">小米</Select.Option>
            <Select.Option value="iflytek">讯飞</Select.Option>
            <Select.Option value="anthropic">Anthropic</Select.Option>
          </Select>
        </Form.Item>

        <Form.Item name="name" label="名称">
          <Input placeholder="给这个 Key 起个名字（可选）" />
        </Form.Item>

        <Form.Item name="api_key" label="API Key">
          <Input.Password placeholder="留空则保留当前密钥" />
        </Form.Item>

        <Form.Item name="openai_url" label="OpenAI 兼容端点">
          <Input placeholder={openaiPlaceholder} />
        </Form.Item>

        <Form.Item name="claude_url" label="Claude 兼容端点">
          <Input placeholder={claudePlaceholder} />
        </Form.Item>

        <Form.Item name="models" label="支持的模型">
          <Select
            mode="tags"
            placeholder="输入模型名称后回车"
            options={presetModels.map(m => ({ label: m, value: m }))}
          />
        </Form.Item>

        <div className="form-row">
          <Form.Item name="tpm_limit" label="TPM 限制">
            <InputNumber min={0} placeholder="0 = 不限" />
          </Form.Item>
          <Form.Item name="rpm_limit" label="RPM 限制">
            <InputNumber min={0} placeholder="0 = 不限" />
          </Form.Item>
        </div>

        <Form.Item name="source" label="来源">
          <Input placeholder="例如：linux.do" />
        </Form.Item>

        <Form.Item name="note" label="备注">
          <Input.TextArea rows={2} placeholder="备注信息（可选）" />
        </Form.Item>
      </Form>
    </Modal>
  )
}
